name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          mkdir -p ./artifacts
          go build ./cmd/natandb
          GOOS=linux GOARCH=amd64 go build -o ./artifacts/natandb ./cmd/natandb
          GOOS=windows GOARCH=amd64 go build -o ./artifacts/natandb.exe ./cmd/natandb

      - name: Test
        run: go test -v ./...
